[package]
name = "rpma"
version = "0.1.0"
edition = "2024"

[dependencies]
aes = "0.8.4"
anyhow = "1.0.98"
ctr = "0.9.2"
hex-literal = "1.0.0"
hkdf = "0.12.4"
rand = "0.9.2"
sha2 = "0.10.9"
subtle = "2.6.1"
x25519-dalek = { version = "2.0.1", features = ["static_secrets"] }
